space => tab

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5,10 +5,10 @@
 # Make sure cmake is available.
 if command -v cmake >/dev/null 2>&1;
 then
-  CMAKE=cmake
+	CMAKE=cmake
 else
-  echo "Error - cmake is not available!"
-  exit 2
+	echo "Error - cmake is not available!"
+	exit 2
 fi
 
 
@@ -19,23 +19,23 @@ prefix=/usr/local
 # Parse the args
 for i in "$@"
 do
-  case $i in
-    --help )          help=true ;;
-    --debug )         build="Debug" ;;
-    --release )       build="Release" ;;
-    --prefix=* )      prefix="${i#--prefix=}" ;;
-    * )               echo "Unrecognised argument $i" ;;
-  esac
+	case $i in
+		--help )          help=true ;;
+		--debug )         build="Debug" ;;
+		--release )       build="Release" ;;
+		--prefix=* )      prefix="${i#--prefix=}" ;;
+		* )               echo "Unrecognised argument $i" ;;
+	esac
 done
 
 if [ "$help" = "true" ]
 then
-  echo
-  echo "--help              Show this message."
-  echo "--debug             Configure debug build."
-  echo "--release           Configure release build."
-  echo "--prefix=path       Installation prefix."
-  exit 0
+	echo
+	echo "--help              Show this message."
+	echo "--debug             Configure debug build."
+	echo "--release           Configure release build."
+	echo "--prefix=path       Installation prefix."
+	exit 0
 fi
 
 echo "-- Configuring project"
